### ISSUE TITLE
Колбэки для текстовых аргументов (1.1)

### ISSUE THREAD

**Issue by deknowny** [deknowny/vkquick#52]
Колбэки -- дополнительные валидаторы для текстовых аргументов

```python
import vkquick as vq


@vq.Command(names="foo")
def foo(arg: vq.Integer):
    return f"Arg is {arg}"


@foo.argument_callback
def arg(ctx, value):
    if value > 10:
        return vq.Decision(True, "Значение больше 10"
    return vq.Decision(False, "Значение меньше 10")   
```

Теперь если передать значение меньше 10, то обработка провалится. Вся необходимая информация появится в дебаггере, пользователь осведомится

Если же нужно как-то изменить аргумент, можно поменять его через контекст

`ctx.reaction_arguments.arg = float(value)`

Колбэки вызываются после того, как инициализированы все аргументы команды

Текст из `Decision` (если передан False) по умолчанию будет отправляться пользователю в ответ. Отключить это можно по специальному флагу (для конкретного колбэка)

**Comment by Rhinik** [comment]
Уже будут встроены два готовых колбека


`check_user_is_chat_member`: проверяет пользователя, является ли тот участником чата

`check_user_exists`: Проверяет переданное значение в виде пользователя (упоминание, ссылка, айди, скрин нейм) на то, что это является настоящим пользователем


Дополнение: на один аргумент можно передать несколько колбэков

**Comment by deknowny** [comment]
Добавлены в 1.0
