### ISSUE TITLE
Предложение: Return Manager

### ISSUE THREAD

**Issue by lordralinc** [deknowny/vkquick#89]
Описание функциональности: Этот менеджер будет обрабатывать то, что возвращается из хендлеров. Например: если вернется строка то она будет отправлена как сообщение.

Референс: https://vkbottle.readthedocs.io/ru/latest/high-level/handling/return-manager/

**Comment by deknowny** [comment]
Спасибо за pull request и уделенное время!

Я считаю ретурн менеджер излишним нагромождением и вижу решение в обличие обычного декоратора достаточно компактным и гибки. Мне не нравится подход с изобретением своих классов для обработки того, что происходит в питоне

Сейчас по умолчанию каждая команда, которая возвращает текст, отправляет его в ответ тому же пользователю, который команду вызвал. Для обработчиков нажатий callback-кнопок возвращающаяся строка показывается в snack-bar окне

***
Пример с использованием декоратора: допустим, вам нужно добавить флаг `disable_mentions=True` в сообщение

Пример команды ниже добавит этот флаг в ответ, поэтому пользователь не получит уведомление об упоминании

```python
import vkquick as vq


app = vq.App()

def add_disable_mentions_flag(func):
    async def wrapper(ctx, **kwargs):
        response = await func(ctx, **kwargs)
        await ctx.reply(response, disable_mentions=True)
    return wrapper

@app.command("/hi")
@add_disable_mentions_flag
async def greeting(ctx: vq.NewMessage):
    sender = await ctx.fetch_sender(vq.User)
    return f"Hello, {sender:@[fullname]}"       
```
Если вам кажется подход с созданием декораторов вручную, вы можете использовать библиотеки, упрощающие создание декораторов, например, [decorators](https://pypi.org/project/decorators/)

P.S. По умолчанию, квик добавляет этот флаг при отправке сообщений автоматически

**Comment by deknowny** [comment]
К тому же, определение поведения `return` порой может быть не так явно. По возможности, рекомендую просто создать отдельную функцию или  депенденси, куда вы и сможете передавать строку, получая ожидаемые результат

**Comment by lordralinc** [comment]
Первая проблема которую я вижу сразу, это добавление как минимум **2х лишних строк** к каждому хендлеру (импорт + декоратор). В ключевых особенностях vkquick указано `Компактность кода: Разработка требует меньше времени в несколько раз, код становится короче`. Не лучше ли написать `Return Manager` и указать его в `__init__` App'a один раз, чем написать такой же декоратор, и каждый раз его импортировать?

Вторая: Необходимость указывать `ctx: vq.NewMessage` в каждом хендлере, даже если хендлер НЕ требует этой переменной (одна из причин из-за которой я решил перейти с vkbottle на vkquick, это как раз отсутствие лишних переменных в аннотациях функций. Мелочь, а приятно).

А так Return Manager'ы очень удобный интерфейс изменения поведения фреймворка.

**Comment by lordralinc** [comment]
На примере [Павука](https://vk.com/kvazar_04)

Добавление `forward` в чатах (в лс этого не требуется от слова совсем)
Добавление `keyboard` -- навигационная клавиатура, ака `меню`
Разбиение смс на части по 4к символов (обход ограничения вк)

**Comment by deknowny** [comment]
Решение в обличие класса с такими декораторами действительно необходимо? Будет ли достаточно одной функции, которая принимает контекст и возвращаемое хэндлером значение?

**Comment by lordralinc** [comment]
Я предоставил лишь идею и референс, методы реализации остаются за Вами, это же Ваш фремворк)

**Comment by deknowny** [comment]
Спасибо, я подумаю над этим вопросом. Ишью оставлю открытым

**Comment by deknowny** [comment]
> На примере [Павука](https://vk.com/kvazar_04)
> 
> 
> 
> Добавление `forward` в чатах (в лс этого не требуется от слова совсем)
> 
> Добавление `keyboard` -- навигационная клавиатура, ака `меню`
> 
> Разбиение смс на части по 4к символов (обход ограничения вк)
> 
> 
> 
> Этим занимается ReturnManager.

Вы можете сделать функцию, которую будете эвейтить и в которую будете передавать контекст нового сообщения

Ретурн менеджер -- неявная логика. Неявным образом сообщение меняется, что может привести к недопониманию

Эвейт своей функции -- явная логика. Я видел, как ребята оборачивают текст сообщения своими функциями, передавая туда контекст, чтобы избавиться от бойлерплейт вставок в сообщение/модификации текста сообщения

Заключение: ретурн менеджер -- излишняя абстракция для библиотеки, чья логика должна быть реализована исключительно самим пользователем

**Comment by deknowny** [comment]
Подразумеваю, вопрос исчерпан
