### ISSUE TITLE
Python 3.10: Ошибка импорта collections

### ISSUE THREAD

**Issue by Unicod3r** [deknowny/vkquick#94]
В новой версии Python модуль collections переименовали в collections.abc. Думаю, дальнейшие объяснения излишни.

```
Traceback (most recent call last):
  File "/home/u/src/original/daybook-notifier/main.py", line 4, in <module>
    import vkquick as vq
  File "/home/u/.local/lib/python3.10/site-packages/vkquick/__init__.py", line 8, in <module>
    from .api import API
  File "/home/u/.local/lib/python3.10/site-packages/vkquick/api.py", line 15, in <module>
    import attrdict
  File "/home/u/.local/lib/python3.10/site-packages/attrdict/__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "/home/u/.local/lib/python3.10/site-packages/attrdict/mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

Решено: снизьте версию Python/дождитесь обновления attrdict.

**Comment by Unicod3r** [comment]
P. S. https://stackoverflow.com/a/71438295

**Comment by Unicod3r** [comment]
P. S. S. Ошибка оказывается не у вас, нужно ждать обновления attrdict...

**Comment by deknowny** [comment]
Спасибо за issue!

Используемая вами версия vkquick -- 0.2, на текущий момент она больше не поддерживается. Используемый там подход с attrdict зависит от некоторой библиотеки, использующей устаревший подход к импорту интерфейсов. Если вам нужна именно версия 0.2, мы будем рады, если вы предложите PR, где зависимость будет использоваться с вашего форка, в котором исправятся импорты. Репозиторий с attrdict заархивирован и не принимает предложений по обновлению

Актуальная версия продукта -- 1.0. Инструкцию, как установить ее с гитхаба, можно найти в README и [актуальной, но не полной документации](https://vkquick.rtfd.io)

Если есть еще вопросы, можете вступить в нашу беседу в вконтакте и обсудить что-то в формате живого общения

**Comment by deknowny** [comment]
Могу закрывать issue?

**Comment by Unicod3r** [comment]
Да. Только ещё один вопрос: почему в pip такая старая версия?

**Comment by deknowny** [comment]
1.0 находится в состоянии пре-релиза и еще на загружался в PyPI, однако вы все еще можете установить библиотеку версии 1.0 используя pip, это не критично.

**Comment by Unicod3r** [comment]
**thx**
